# Generated by Django 4.1.3 on 2022-11-30 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricanteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.fabricantemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehcleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=130)),
                ('image', models.ImageField(upload_to='media')),
                ('cor', models.CharField(max_length=30)),
                ('preco', models.FloatField()),
                ('disponivel', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.modelomodel')),
            ],
        ),
    ]
